[build]
  base    = "frontend"     # Specify the subdirectory where your Next.js project resides
  publish = ".next"  # Output directory within the subdirectory
  command = "npm run build"   # Your build command within the subdirectory (usually `npm run build`)

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[dev]
  command = "next dev"
  port = 3000
  publish = ".next"